package ru.geekbrains.safia.web.mvc.app;// Generated by Selenium IDE
import org.junit.Assert;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class LogoutNegativeTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.gecko.driver", "/home/safia/courses/Nail/geckodriver-v0.28.0-linux64/geckodriver");
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void negative() {
    driver.get("http://localhost:8080/mvc-app/login");
    driver.manage().window().setSize(new Dimension(1000, 864));
    login("123", "fsafia");
    WebElement alertBadCredentialsLogin = driver.findElement(By.cssSelector(".alert"));
    Assert.assertEquals("Bad credentials", alertBadCredentialsLogin.getText());

    login("fsafia", "123");
    WebElement alertBadCredentialsPasswordNegativ = driver.findElement(By.cssSelector(".alert"));
    Assert.assertEquals("Bad credentials", alertBadCredentialsPasswordNegativ.getText());

  }

  private void login(String username, String password) {
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys(username);
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys(password);
    driver.findElement(By.cssSelector(".btn")).click();
  }
}
